apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          # image: us.gcr.io/quantum-theme-280313/tickets
          image: chihweidavidliu/tickets
          env:
            - name: JWT_KEY # the name we will use to reference this variable within tickets
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # the name of the secret we created
                  key: JWT_KEY # the key within the secret whose value we will assign to this env variable

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  type: ClusterIP
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
